/**
 * M17 Accounts â€” DTOs that mirror src/backend/.../Ulp.Accounting.Application/Contracts.cs.
 * Generated by hand to keep dependency surface small. Keep in sync with backend.
 */

export type AccountClass    = 'Asset' | 'Liability' | 'Equity' | 'Revenue' | 'Expense';
export type PeriodStatus    = 'Future' | 'Open' | 'SoftClose' | 'Closed';
export type InvoiceStatus   = 'Draft' | 'PendingApproval' | 'Approved' | 'Posted'
                            | 'PartiallyPaid' | 'Paid' | 'Overdue' | 'WrittenOff' | 'Void';
export type BillStatus      = 'Draft' | 'PendingApproval' | 'Approved' | 'Posted'
                            | 'PartiallyPaid' | 'Paid' | 'Overdue' | 'Disputed' | 'Cancelled';
export type ReceiptStatus   = 'Received' | 'PartiallyMatched' | 'Matched' | 'Refunded';
export type PaymentMethod   = 'Cash' | 'Cheque' | 'BankTransfer' | 'Card'
                            | 'Upi' | 'Neft' | 'Rtgs' | 'Imps' | 'Nach' | 'Ach' | 'Wire' | 'Other';
export type PaymentStatus   = 'Pending' | 'Approved' | 'Sent' | 'Cleared' | 'Failed' | 'Cancelled';
export type ExportType      = 'Lut' | 'Wpay' | 'None';
export type IrnStatus       = 'Generated' | 'Cancelled' | 'Failed';
export type JournalType     = 'General' | 'ArInvoice' | 'ApBill' | 'Payment' | 'Receipt'
                            | 'PeriodClose' | 'FxReval' | 'OpeningBalance' | 'Adjustment';
export type DebitCredit     = 'Dr' | 'Cr';

export interface AccountDto {
  id: number; tenantId: number; countryCode: string;
  accountCode: string; accountName: string; accountClass: AccountClass;
  parentAccountId: number | null; isControlAccount: boolean; isPostable: boolean;
  defaultCurrency: string; isActive: boolean;
}

export interface PeriodDto {
  id: number; fiscalYear: number; periodNumber: number; periodName: string;
  startDate: string; endDate: string; status: PeriodStatus;
  closedAt: string | null; reopenedCount: number;
}

export interface InvoiceLineDto {
  id: number; invoiceId: number; lineNumber: number; description: string;
  hsnCode: string | null; quantity: number; uomCode: string | null;
  unitPriceAmount: number; unitPriceCurrency: string; lineAmount: number;
  taxClass: string | null; taxRatePct: number | null; taxAmount: number;
  accountId: number | null;
}

export interface InvoiceExtInDto {
  placeOfSupply: string | null; isIntraState: boolean;
  cgstAmount: number; sgstAmount: number; igstAmount: number; cessAmount: number;
  reverseCharge: boolean; isExport: boolean; exportType: ExportType;
}

export interface IrnDto {
  irnValue: string; ackNo: string; ackDate: string; irpProvider: string; status: IrnStatus;
}

export interface InvoiceDto {
  id: number; tenantId: number; countryCode: string;
  invoiceNumber: string; invoiceDate: string; dueDate: string;
  customerPartyId: number; customerName: string | null;
  currency: string; funcCurrency: string; fxRate: number;
  subtotalAmount: number; taxAmount: number; discountAmount: number;
  totalAmount: number; paidAmount: number;
  paymentTerms: string | null; notes: string | null;
  status: InvoiceStatus; postedJournalId: number | null; postedAt: string | null;
  createdAt: string; modifiedAt: string;
  lines: InvoiceLineDto[] | null;
  indiaExt: InvoiceExtInDto | null;
  irn: IrnDto | null;
}

export interface BillLineDto {
  id: number; billId: number; lineNumber: number; description: string;
  hsnCode: string | null; quantity: number; uomCode: string | null;
  unitPriceAmount: number; lineAmount: number;
  taxClass: string | null; taxRatePct: number | null; taxAmount: number;
  accountId: number | null;
}

export interface BillExtInDto {
  tdsSectionCode: string | null; tdsRatePct: number | null; tdsAmount: number;
  vendorPan: string | null; vendorGstin: string | null; isReverseCharge: boolean;
}

export interface BillDto {
  id: number; tenantId: number; countryCode: string;
  billNumber: string; internalNumber: string; billDate: string; dueDate: string;
  vendorPartyId: number; vendorName: string | null;
  currency: string; funcCurrency: string; fxRate: number;
  subtotalAmount: number; taxAmount: number; withholdingAmount: number;
  totalAmount: number; paidAmount: number;
  notes: string | null; status: BillStatus;
  postedJournalId: number | null; postedAt: string | null;
  createdAt: string; modifiedAt: string;
  lines: BillLineDto[] | null;
  indiaExt: BillExtInDto | null;
}

export interface ReceiptMatchDto {
  id: number; receiptId: number; invoiceId: number; matchedAmount: number; matchedAt: string; isAuto: boolean;
}

export interface ReceiptDto {
  id: number; tenantId: number; countryCode: string;
  receiptNumber: string; receiptDate: string;
  customerPartyId: number; customerName: string | null;
  amount: number; currency: string; paymentMethod: PaymentMethod;
  bankReference: string | null; unmatchedAmount: number; status: ReceiptStatus;
  createdAt: string; modifiedAt: string;
  matches: ReceiptMatchDto[] | null;
}

export interface PaymentAllocDto {
  id: number; paymentId: number; billId: number; allocatedAmount: number;
}

export interface PaymentDto {
  id: number; tenantId: number; countryCode: string;
  paymentNumber: string; paymentDate: string;
  vendorPartyId: number; vendorName: string | null;
  amount: number; currency: string;
  withholdingAmount: number; netAmount: number;
  paymentMethod: PaymentMethod; bankReference: string | null;
  status: PaymentStatus;
  createdAt: string; modifiedAt: string;
  allocations: PaymentAllocDto[] | null;
}

export interface JournalLineDto {
  id: number; journalId: number; lineNumber: number; accountId: number; accountCode: string;
  amountOrig: number; currencyOrig: string; amountFunc: number; currencyFunc: string;
  fxRate: number; fxRateDate: string; debitCredit: DebitCredit;
  partyId: number | null; reference: string | null; description: string | null;
}

export interface JournalDto {
  id: number; tenantId: number; journalNumber: string; journalType: JournalType;
  postingDate: string; periodId: number; description: string | null;
  sourceModule: string | null; sourceRecordId: number | null;
  isPosted: boolean; isReversed: boolean;
  createdAt: string; postedAt: string | null;
  lines: JournalLineDto[] | null;
}

export interface TrialBalanceRowDto {
  accountId: number; accountCode: string; accountName: string; accountClass: AccountClass;
  debit: number; credit: number; balance: number;
}

export interface TrialBalanceDto {
  periodId: number; periodName: string; startDate: string; endDate: string;
  funcCurrency: string; totalDebits: number; totalCredits: number;
  rows: TrialBalanceRowDto[];
}

export interface IncomeStatementRowDto { accountCode: string; accountName: string; amount: number; }

export interface IncomeStatementDto {
  fromPeriodId: number; toPeriodId: number; funcCurrency: string;
  totalRevenue: number; totalExpenses: number; netIncome: number;
  revenue: IncomeStatementRowDto[]; expenses: IncomeStatementRowDto[];
}

/* ===================== Request DTOs (mirror Ulp.Accounting.Application) ===================== */

export interface CreateInvoiceLineRequest {
  description: string;
  hsnCode?: string | null;
  quantity: number;
  uomCode?: string | null;
  unitPriceAmount: number;
  unitPriceCurrency: string;
  accountId?: number | null;
}

export interface CreateInvoiceRequest {
  countryCode: string;
  invoiceNumber: string;
  invoiceDate: string;       // ISO date YYYY-MM-DD
  dueDate: string;
  customerPartyId: number;
  currency: string;
  funcCurrency: string;
  fxRate: number;
  paymentTerms?: string | null;
  notes?: string | null;
  lines: CreateInvoiceLineRequest[];
  // India-specific:
  placeOfSupply?: string | null;
  isExport?: boolean | null;
  exportType?: ExportType | null;
}

export interface CreateBillLineRequest {
  description: string;
  hsnCode?: string | null;
  quantity: number;
  uomCode?: string | null;
  unitPriceAmount: number;
  accountId?: number | null;
}

export interface CreateBillRequest {
  countryCode: string;
  billNumber: string;        // vendor's number
  internalNumber: string;    // our number
  billDate: string;
  dueDate: string;
  vendorPartyId: number;
  currency: string;
  funcCurrency: string;
  fxRate: number;
  notes?: string | null;
  lines: CreateBillLineRequest[];
  tdsSectionCode?: string | null;
  vendorPan?: string | null;
  vendorGstin?: string | null;
  isReverseCharge?: boolean | null;
}

export interface CreateReceiptRequest {
  countryCode: string;
  receiptNumber: string;
  receiptDate: string;
  customerPartyId: number;
  amount: number;
  currency: string;
  paymentMethod: PaymentMethod;
  bankReference?: string | null;
  notes?: string | null;
}

export interface CreatePaymentRequest {
  countryCode: string;
  paymentNumber: string;
  paymentDate: string;
  vendorPartyId: number;
  amount: number;
  currency: string;
  withholdingAmount: number;
  paymentMethod: PaymentMethod;
  bankReference?: string | null;
  notes?: string | null;
  billIds: number[];
}

// CreateGeneralExpenseRequest lives in accounting-ext-types alongside GeneralExpenseDto.

export interface BalanceSheetRowDto { accountCode: string; accountName: string; amount: number; }

export interface BalanceSheetDto {
  asOfPeriodId: number; funcCurrency: string;
  totalAssets: number; totalLiabilities: number; totalEquity: number;
  assets: BalanceSheetRowDto[]; liabilities: BalanceSheetRowDto[]; equity: BalanceSheetRowDto[];
}

export interface AgingBucketDto {
  partyId: number; partyName: string; currency: string;
  current: number; bucket1To30: number; bucket31To60: number; bucket61To90: number; bucketOver90: number;
  total: number;
}
